// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../util.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `entropy_source`, `poly1305_tag_empty_aad`, `strip_receive_auth`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `KnownEntropy`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `get_secure_random_bytes`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `parse_bolt12_invoice`

/// function to fetch bolt12 lightning offer for a given username using DNS query according to BIP-353
Future<String?> fetchBolt12OfferUriFromUsername({
  required Network network,
  required String username,
}) => MannaCore.instance.api.crateBoltzBolt12FetchBolt12OfferUriFromUsername(
  network: network,
  username: username,
);

Future<String> signSchnorr({
  required String data,
  required KeyPair signingKey,
}) => MannaCore.instance.api.crateBoltzBolt12SignSchnorr(
  data: data,
  signingKey: signingKey,
);

class Bolt12OfferCreationParam {
  final LiquidWallet liquidWallet;
  final String? issuerName;
  final String? description;

  const Bolt12OfferCreationParam({
    required this.liquidWallet,
    this.issuerName,
    this.description,
  });

  @override
  int get hashCode =>
      liquidWallet.hashCode ^ issuerName.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Bolt12OfferCreationParam &&
          runtimeType == other.runtimeType &&
          liquidWallet == other.liquidWallet &&
          issuerName == other.issuerName &&
          description == other.description;
}

class DecodedBolt12InvoiceRequest {
  final String payerSigningKey;
  final Network network;
  final BigInt? amountMsats;
  final BigInt? quantity;
  final String? payerNote;

  const DecodedBolt12InvoiceRequest({
    required this.payerSigningKey,
    required this.network,
    this.amountMsats,
    this.quantity,
    this.payerNote,
  });

  static DecodedBolt12InvoiceRequest decode({
    required String invoiceRequestHex,
  }) =>
      MannaCore.instance.api.crateBoltzBolt12DecodedBolt12InvoiceRequestDecode(
        invoiceRequestHex: invoiceRequestHex,
      );

  @override
  int get hashCode =>
      payerSigningKey.hashCode ^
      network.hashCode ^
      amountMsats.hashCode ^
      quantity.hashCode ^
      payerNote.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedBolt12InvoiceRequest &&
          runtimeType == other.runtimeType &&
          payerSigningKey == other.payerSigningKey &&
          network == other.network &&
          amountMsats == other.amountMsats &&
          quantity == other.quantity &&
          payerNote == other.payerNote;
}
