// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../boltz.dart';
import '../frb_generated.dart';
import '../util.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'swap_transaction.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `get_chain`, `get_liquid_address`, `get_reverse`, `get_submarine`, `send_notification_to_other_devices`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PairCache`

Future<String> getSubmarineJson({
  required ApiConfig apiConfig,
  required Network network,
}) => MannaCore.instance.api.crateBoltzProcessSwapGetSubmarineJson(
  apiConfig: apiConfig,
  network: network,
);

Future<String> getReverseJson({
  required ApiConfig apiConfig,
  required Network network,
}) => MannaCore.instance.api.crateBoltzProcessSwapGetReverseJson(
  apiConfig: apiConfig,
  network: network,
);

Future<String> getChainJson({
  required ApiConfig apiConfig,
  required Network network,
}) => MannaCore.instance.api.crateBoltzProcessSwapGetChainJson(
  apiConfig: apiConfig,
  network: network,
);

/// call this function to process the swap based on the status, the passed swap should have updated status
///
/// returns None if swap is not handled else returns updated swap and<br>
///     [Some(true)] if chain swap can be negotiated but automatic negotiation failed and user intervention required.<br>
///     [Some(false)] if refund requires user intervention and automatic refund failed.<br>
///     [None]: swap is processed successfully.
///
/// [device_id] is passed to backend to exclude notification for following device
Future<(Swap, bool?)?> processSwap({
  required Swap swap,
  required BoltzManager boltzManager,
  required String lwkPath,
  required List<LiquidWallet> liquidWallets,
  required FutureOr<void> Function(Swap) onReceivingClaimStart,
  required FutureOr<void> Function(Swap) onReceivingClaimComplete,
  String? deviceId,
}) => MannaCore.instance.api.crateBoltzProcessSwapProcessSwap(
  swap: swap,
  boltzManager: boltzManager,
  lwkPath: lwkPath,
  liquidWallets: liquidWallets,
  onReceivingClaimStart: onReceivingClaimStart,
  onReceivingClaimComplete: onReceivingClaimComplete,
  deviceId: deviceId,
);

/// returns updated swap and true if swap is at its final state
(Swap, bool) isFinalSwapState({required Swap swap}) =>
    MannaCore.instance.api.crateBoltzProcessSwapIsFinalSwapState(swap: swap);
