// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../util.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `as_str`, `fetch_and_link_swap_transaction_inner_call`, `find_lockup_output_index`, `get_public_address`, `get_script_pub_key_hex`, `is_non_cooperative_refund`, `push_swap_transaction`, `spends_output`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EsploraTransaction`, `EsploraVin`, `EsploraVout`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`

/// fetches swap transactions from esplora and return swap with linked swap transactions.
Future<Swap> fetchAndLinkSwapTransactions({
  required Swap swap,
  required ApiConfig apiConfig,
}) => MannaCore.instance.api
    .crateBoltzSwapTransactionFetchAndLinkSwapTransactions(
      swap: swap,
      apiConfig: apiConfig,
    );

class SwapTransaction {
  final String txId;
  final Chain chain;
  final SwapTransactionType txType;
  final bool isUser;

  const SwapTransaction({
    required this.txId,
    required this.chain,
    required this.txType,
    required this.isUser,
  });

  @override
  int get hashCode =>
      txId.hashCode ^ chain.hashCode ^ txType.hashCode ^ isUser.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapTransaction &&
          runtimeType == other.runtimeType &&
          txId == other.txId &&
          chain == other.chain &&
          txType == other.txType &&
          isUser == other.isUser;
}

enum SwapTransactionType { lockup, claim, refund }
