// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../util.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'swap_transaction.dart';

// These functions are ignored because they are not marked as `pub`: `as_str`, `get_boltz_client`, `get_config`, `get_electrum_url`, `get_esplora_url`, `get_server_api_endpoint`, `get_supabase_config`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `try_into`, `try_into`, `try_into`, `try_into`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `bitcoin`, `liquid`, `to_chain`

/// parses bolt11 invoice, if you want to extract bip21 address used to create this lightning invoice use [Self::from_bolt11_invoice] instead.
DecodedInvoice decodeBolt11Invoice({required String invoice}) =>
    MannaCore.instance.api.crateBoltzTypesDecodeBolt11Invoice(invoice: invoice);

/// boltz can not create submarine swap paying lightning invoice created by reverse swap.
/// so Pass boltz_url to fetch bip21 address which is encoded by sender and which you can directly pay
Future<DecodedInvoice> decodeBolt11InvoiceBip21({
  required String invoice,
  String? boltzUrl,
}) => MannaCore.instance.api.crateBoltzTypesDecodeBolt11InvoiceBip21(
  invoice: invoice,
  boltzUrl: boltzUrl,
);

DecodedInvoice decodeBolt12Invoice({required String invoice}) =>
    MannaCore.instance.api.crateBoltzTypesDecodeBolt12Invoice(invoice: invoice);

/// function to validate bolt12 lightning offer
Future<DecodedBolt12Offer> decodeBolt12Offer({required String offer}) =>
    MannaCore.instance.api.crateBoltzTypesDecodeBolt12Offer(offer: offer);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MasterSwapKey>>
abstract class MasterSwapKey implements RustOpaqueInterface {
  Future<KeyPair> deriveBtcChildKey({required BigInt index});

  Future<KeyPair> deriveLiquidChildKey({required BigInt index});

  static Future<MasterSwapKey> fromMnemonic({
    required String mnemonic,
    String? passphrase,
    required Network network,
  }) => MannaCore.instance.api.crateBoltzTypesMasterSwapKeyFromMnemonic(
    mnemonic: mnemonic,
    passphrase: passphrase,
    network: network,
  );

  static Future<MasterSwapKey> fromWalletMnemonic({
    required String walletMnemonic,
    String? walletPassphrase,
    required Network network,
  }) => MannaCore.instance.api.crateBoltzTypesMasterSwapKeyFromWalletMnemonic(
    walletMnemonic: walletMnemonic,
    walletPassphrase: walletPassphrase,
    network: network,
  );

  Future<KeyPair> getBolt12SigningKey({required int index});

  Future<String> getSwapXpub();

  String toMnemonicString();
}

class ApiConfig {
  final NetworkConfig mainnet;
  final NetworkConfig testnet;
  final NetworkConfig regtest;

  const ApiConfig({
    required this.mainnet,
    required this.testnet,
    required this.regtest,
  });

  static ApiConfig fromJson({required String json}) =>
      MannaCore.instance.api.crateBoltzTypesApiConfigFromJson(json: json);

  String toJson() =>
      MannaCore.instance.api.crateBoltzTypesApiConfigToJson(that: this);

  @override
  int get hashCode => mainnet.hashCode ^ testnet.hashCode ^ regtest.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiConfig &&
          runtimeType == other.runtimeType &&
          mainnet == other.mainnet &&
          testnet == other.testnet &&
          regtest == other.regtest;
}

enum Chain { bitcoin, liquid }

class ChainSwap {
  final ChainSwapDirection direction;
  final KeyPair claimKeys;
  final KeyPair refundKeys;
  final ChainSwapData lockupDetails;
  final ChainSwapData claimDetails;

  const ChainSwap({
    required this.direction,
    required this.claimKeys,
    required this.refundKeys,
    required this.lockupDetails,
    required this.claimDetails,
  });

  @override
  int get hashCode =>
      direction.hashCode ^
      claimKeys.hashCode ^
      refundKeys.hashCode ^
      lockupDetails.hashCode ^
      claimDetails.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChainSwap &&
          runtimeType == other.runtimeType &&
          direction == other.direction &&
          claimKeys == other.claimKeys &&
          refundKeys == other.refundKeys &&
          lockupDetails == other.lockupDetails &&
          claimDetails == other.claimDetails;
}

class ChainSwapData {
  final SwapTreeData swapTree;
  final String lockupAddress;
  final String serverPublicKey;
  final int timeoutBlockHeight;
  final BigInt amount;
  final String? blindingKey;
  String? refundAddress;
  String? claimAddress;
  final String? bip21;

  ChainSwapData({
    required this.swapTree,
    required this.lockupAddress,
    required this.serverPublicKey,
    required this.timeoutBlockHeight,
    required this.amount,
    this.blindingKey,
    this.refundAddress,
    this.claimAddress,
    this.bip21,
  });

  @override
  int get hashCode =>
      swapTree.hashCode ^
      lockupAddress.hashCode ^
      serverPublicKey.hashCode ^
      timeoutBlockHeight.hashCode ^
      amount.hashCode ^
      blindingKey.hashCode ^
      refundAddress.hashCode ^
      claimAddress.hashCode ^
      bip21.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChainSwapData &&
          runtimeType == other.runtimeType &&
          swapTree == other.swapTree &&
          lockupAddress == other.lockupAddress &&
          serverPublicKey == other.serverPublicKey &&
          timeoutBlockHeight == other.timeoutBlockHeight &&
          amount == other.amount &&
          blindingKey == other.blindingKey &&
          refundAddress == other.refundAddress &&
          claimAddress == other.claimAddress &&
          bip21 == other.bip21;
}

enum ChainSwapDirection { btcToLbtc, lbtcToBtc }

class DecodedBolt12Offer {
  final String id;
  final String parsedOffer;
  final bool isExpired;
  final List<Network> networks;
  final BigInt? amount;
  final String? description;
  final String? issuer;

  const DecodedBolt12Offer({
    required this.id,
    required this.parsedOffer,
    required this.isExpired,
    required this.networks,
    this.amount,
    this.description,
    this.issuer,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      parsedOffer.hashCode ^
      isExpired.hashCode ^
      networks.hashCode ^
      amount.hashCode ^
      description.hashCode ^
      issuer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedBolt12Offer &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          parsedOffer == other.parsedOffer &&
          isExpired == other.isExpired &&
          networks == other.networks &&
          amount == other.amount &&
          description == other.description &&
          issuer == other.issuer;
}

class DecodedInvoice {
  final BigInt msats;
  final BigInt expiresAt;
  final bool isExpired;
  final Network network;
  final (String, BigInt)? bip21;
  final String preimageHash;
  final String? description;

  /// bolt12 offer issuer
  final String? issuer;

  const DecodedInvoice({
    required this.msats,
    required this.expiresAt,
    required this.isExpired,
    required this.network,
    this.bip21,
    required this.preimageHash,
    this.description,
    this.issuer,
  });

  @override
  int get hashCode =>
      msats.hashCode ^
      expiresAt.hashCode ^
      isExpired.hashCode ^
      network.hashCode ^
      bip21.hashCode ^
      preimageHash.hashCode ^
      description.hashCode ^
      issuer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedInvoice &&
          runtimeType == other.runtimeType &&
          msats == other.msats &&
          expiresAt == other.expiresAt &&
          isExpired == other.isExpired &&
          network == other.network &&
          bip21 == other.bip21 &&
          preimageHash == other.preimageHash &&
          description == other.description &&
          issuer == other.issuer;
}

class ExtraSwapFee {
  final String id;
  final double percentage;

  const ExtraSwapFee({required this.id, required this.percentage});

  @override
  int get hashCode => id.hashCode ^ percentage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtraSwapFee &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          percentage == other.percentage;
}

/// mirrors
class LeafData {
  final String output;
  final int version;

  const LeafData({required this.output, required this.version});

  @override
  int get hashCode => output.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LeafData &&
          runtimeType == other.runtimeType &&
          output == other.output &&
          version == other.version;
}

class NetworkConfig {
  final NetworkEndpoints bitcoin;
  final NetworkEndpoints liquid;
  final String boltzUrl;
  final BigInt boltzFeeCacheTimeoutMs;
  final SupabaseConfig supabase;
  final String serverUrl;
  final String serverApiVersion;

  const NetworkConfig({
    required this.bitcoin,
    required this.liquid,
    required this.boltzUrl,
    required this.boltzFeeCacheTimeoutMs,
    required this.supabase,
    required this.serverUrl,
    required this.serverApiVersion,
  });

  @override
  int get hashCode =>
      bitcoin.hashCode ^
      liquid.hashCode ^
      boltzUrl.hashCode ^
      boltzFeeCacheTimeoutMs.hashCode ^
      supabase.hashCode ^
      serverUrl.hashCode ^
      serverApiVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkConfig &&
          runtimeType == other.runtimeType &&
          bitcoin == other.bitcoin &&
          liquid == other.liquid &&
          boltzUrl == other.boltzUrl &&
          boltzFeeCacheTimeoutMs == other.boltzFeeCacheTimeoutMs &&
          supabase == other.supabase &&
          serverUrl == other.serverUrl &&
          serverApiVersion == other.serverApiVersion;
}

class NetworkEndpoints {
  final String esplora;
  final String electrum;

  const NetworkEndpoints({required this.esplora, required this.electrum});

  @override
  int get hashCode => esplora.hashCode ^ electrum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkEndpoints &&
          runtimeType == other.runtimeType &&
          esplora == other.esplora &&
          electrum == other.electrum;
}

class PreImage {
  final String value;
  final String sha256;
  final String hash160;

  const PreImage({
    required this.value,
    required this.sha256,
    required this.hash160,
  });

  static Future<PreImage> fromString({required String preimage}) => MannaCore
      .instance
      .api
      .crateBoltzTypesPreImageFromString(preimage: preimage);

  static Future<PreImage> generate({required KeyPair keyPair}) =>
      MannaCore.instance.api.crateBoltzTypesPreImageGenerate(keyPair: keyPair);

  @override
  int get hashCode => value.hashCode ^ sha256.hashCode ^ hash160.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PreImage &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          sha256 == other.sha256 &&
          hash160 == other.hash160;
}

class ReverseResponse {
  final String? invoice;
  final SwapTreeData swapTree;
  final String lockupAddress;
  final String refundPublicKey;
  final int timeoutBlockHeight;
  final BigInt onchainAmount;
  final String? blindingKey;

  const ReverseResponse({
    this.invoice,
    required this.swapTree,
    required this.lockupAddress,
    required this.refundPublicKey,
    required this.timeoutBlockHeight,
    required this.onchainAmount,
    this.blindingKey,
  });

  @override
  int get hashCode =>
      invoice.hashCode ^
      swapTree.hashCode ^
      lockupAddress.hashCode ^
      refundPublicKey.hashCode ^
      timeoutBlockHeight.hashCode ^
      onchainAmount.hashCode ^
      blindingKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReverseResponse &&
          runtimeType == other.runtimeType &&
          invoice == other.invoice &&
          swapTree == other.swapTree &&
          lockupAddress == other.lockupAddress &&
          refundPublicKey == other.refundPublicKey &&
          timeoutBlockHeight == other.timeoutBlockHeight &&
          onchainAmount == other.onchainAmount &&
          blindingKey == other.blindingKey;
}

class ReverseSwap {
  final Chain to;
  final KeyPair keys;
  final ReverseResponse swapCreateRes;

  const ReverseSwap({
    required this.to,
    required this.keys,
    required this.swapCreateRes,
  });

  @override
  int get hashCode => to.hashCode ^ keys.hashCode ^ swapCreateRes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ReverseSwap &&
          runtimeType == other.runtimeType &&
          to == other.to &&
          keys == other.keys &&
          swapCreateRes == other.swapCreateRes;
}

class SubmarineResponse {
  final bool acceptZeroConf;
  final String address;
  final String bip21;
  final String claimPublicKey;
  final BigInt expectedAmount;
  final SwapTreeData swapTree;
  final BigInt timeoutBlockHeight;
  final String? blindingKey;

  const SubmarineResponse({
    required this.acceptZeroConf,
    required this.address,
    required this.bip21,
    required this.claimPublicKey,
    required this.expectedAmount,
    required this.swapTree,
    required this.timeoutBlockHeight,
    this.blindingKey,
  });

  @override
  int get hashCode =>
      acceptZeroConf.hashCode ^
      address.hashCode ^
      bip21.hashCode ^
      claimPublicKey.hashCode ^
      expectedAmount.hashCode ^
      swapTree.hashCode ^
      timeoutBlockHeight.hashCode ^
      blindingKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubmarineResponse &&
          runtimeType == other.runtimeType &&
          acceptZeroConf == other.acceptZeroConf &&
          address == other.address &&
          bip21 == other.bip21 &&
          claimPublicKey == other.claimPublicKey &&
          expectedAmount == other.expectedAmount &&
          swapTree == other.swapTree &&
          timeoutBlockHeight == other.timeoutBlockHeight &&
          blindingKey == other.blindingKey;
}

class SubmarineSwap {
  final Chain from;
  final KeyPair keys;
  final String invoice;
  final SubmarineResponse swapCreateRes;

  const SubmarineSwap({
    required this.from,
    required this.keys,
    required this.invoice,
    required this.swapCreateRes,
  });

  @override
  int get hashCode =>
      from.hashCode ^ keys.hashCode ^ invoice.hashCode ^ swapCreateRes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SubmarineSwap &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          keys == other.keys &&
          invoice == other.invoice &&
          swapCreateRes == other.swapCreateRes;
}

class SupabaseConfig {
  final String projectRef;
  final String apiKey;

  const SupabaseConfig({required this.projectRef, required this.apiKey});

  @override
  int get hashCode => projectRef.hashCode ^ apiKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SupabaseConfig &&
          runtimeType == other.runtimeType &&
          projectRef == other.projectRef &&
          apiKey == other.apiKey;
}

class Swap {
  final String id;
  final PlatformInt64 index;
  final String walletId;
  final WalletType walletType;
  final Network network;
  final PreImage preimage;
  BigInt sendAmount;
  BigInt receiveAmount;
  final BigInt creationTime;
  BigInt? completionTime;
  final SubmarineSwap? submarine;
  final ReverseSwap? reverse;
  final ChainSwap? chain;
  String swapStatus;
  String? failureReason;
  String? note;
  BigInt? boltzFee;
  final BigInt? lockupFee;
  final BigInt? claimFee;
  String? refundedAddress;
  BigInt? refundFee;
  List<SwapTransaction> transactions;
  bool isExchangeSwap;
  BigInt? expectedLockupAmount;

  Swap({
    required this.id,
    required this.index,
    required this.walletId,
    required this.walletType,
    required this.network,
    required this.preimage,
    required this.sendAmount,
    required this.receiveAmount,
    required this.creationTime,
    this.completionTime,
    this.submarine,
    this.reverse,
    this.chain,
    required this.swapStatus,
    this.failureReason,
    this.note,
    this.boltzFee,
    this.lockupFee,
    this.claimFee,
    this.refundedAddress,
    this.refundFee,
    required this.transactions,
    required this.isExchangeSwap,
    this.expectedLockupAmount,
  });

  static Swap fromJson({required String json}) =>
      MannaCore.instance.api.crateBoltzTypesSwapFromJson(json: json);

  String toJson() =>
      MannaCore.instance.api.crateBoltzTypesSwapToJson(that: this);

  @override
  int get hashCode =>
      id.hashCode ^
      index.hashCode ^
      walletId.hashCode ^
      walletType.hashCode ^
      network.hashCode ^
      preimage.hashCode ^
      sendAmount.hashCode ^
      receiveAmount.hashCode ^
      creationTime.hashCode ^
      completionTime.hashCode ^
      submarine.hashCode ^
      reverse.hashCode ^
      chain.hashCode ^
      swapStatus.hashCode ^
      failureReason.hashCode ^
      note.hashCode ^
      boltzFee.hashCode ^
      lockupFee.hashCode ^
      claimFee.hashCode ^
      refundedAddress.hashCode ^
      refundFee.hashCode ^
      transactions.hashCode ^
      isExchangeSwap.hashCode ^
      expectedLockupAmount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Swap &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          index == other.index &&
          walletId == other.walletId &&
          walletType == other.walletType &&
          network == other.network &&
          preimage == other.preimage &&
          sendAmount == other.sendAmount &&
          receiveAmount == other.receiveAmount &&
          creationTime == other.creationTime &&
          completionTime == other.completionTime &&
          submarine == other.submarine &&
          reverse == other.reverse &&
          chain == other.chain &&
          swapStatus == other.swapStatus &&
          failureReason == other.failureReason &&
          note == other.note &&
          boltzFee == other.boltzFee &&
          lockupFee == other.lockupFee &&
          claimFee == other.claimFee &&
          refundedAddress == other.refundedAddress &&
          refundFee == other.refundFee &&
          transactions == other.transactions &&
          isExchangeSwap == other.isExchangeSwap &&
          expectedLockupAmount == other.expectedLockupAmount;
}

class SwapTreeData {
  final LeafData claimLeaf;
  final LeafData refundLeaf;

  const SwapTreeData({required this.claimLeaf, required this.refundLeaf});

  @override
  int get hashCode => claimLeaf.hashCode ^ refundLeaf.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SwapTreeData &&
          runtimeType == other.runtimeType &&
          claimLeaf == other.claimLeaf &&
          refundLeaf == other.refundLeaf;
}

class TxFee {
  final BigInt? absolute;
  final double? relative;

  const TxFee({this.absolute, this.relative});

  @override
  int get hashCode => absolute.hashCode ^ relative.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxFee &&
          runtimeType == other.runtimeType &&
          absolute == other.absolute &&
          relative == other.relative;
}

class WebHook {
  final String url;
  final List<String>? statuses;

  const WebHook({required this.url, this.statuses});

  @override
  int get hashCode => url.hashCode ^ statuses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WebHook &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          statuses == other.statuses;
}
