// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../types.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Descriptor {
  const Descriptor();

  /// extracts (xpub, derivationPath) from wallet descriptor string
  static Future<(String, String)?> extractXpub({
    required String descriptorStr,
  }) => MannaCore.instance.api.crateLwkDescriptorDescriptorExtractXpub(
    descriptorStr: descriptorStr,
  );

  static Future<String> greenWalletWatchOnly({required String descriptor}) =>
      MannaCore.instance.api.crateLwkDescriptorDescriptorGreenWalletWatchOnly(
        descriptor: descriptor,
      );

  /// Create new wpkh confidential descriptor based on Slip77 blinding key derivation
  static Future<String> newConfidential({
    required Network network,
    required String mnemonic,
  }) => MannaCore.instance.api.crateLwkDescriptorDescriptorNewConfidential(
    network: network,
    mnemonic: mnemonic,
  );

  /// parse multi-line as well as single line wallet descriptor and returns single line descriptor that can be used to initialize wallet.
  static Future<String> parseDescriptor({required String descriptorStr}) =>
      MannaCore.instance.api.crateLwkDescriptorDescriptorParseDescriptor(
        descriptorStr: descriptorStr,
      );

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Descriptor && runtimeType == other.runtimeType;
}
