// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../util.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `get_wallet`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Wallet>>
abstract class Wallet implements RustOpaqueInterface {
  /// Get an address from a specific index
  Future<Address> address({required int index});

  /// Get the last unused address from the wallet
  Future<Address> addressLastUnused();

  /// Get balances for a wallet.
  Future<List<Balance>> balances();

  /// Get the blinding key string for the wallet
  Future<String> blindingKey();

  /// Build a LBTC transaction
  Future<String> buildLbtcTx({
    required List<(String, BigInt)> recipients,
    required double feeRate,
    required bool drain,
  });

  /// Decode a transaction given a PSET
  Future<DecodedPset> decodeTx({required String psetString});

  /// Get the descriptor string for the wallet
  Future<String> descriptor();

  /// Get storage path of persister of wallet
  static Future<String> getWalletFsPath({
    required Network network,
    required String descriptor,
  }) => MannaCore.instance.api.crateLwkWalletWalletGetWalletFsPath(
    network: network,
    descriptor: descriptor,
  );

  /// Initializes a wallet from a specific db path and descriptor
  static Future<Wallet> init({
    required Network network,
    required String dbpath,
    required String descriptorStr,
  }) => MannaCore.instance.api.crateLwkWalletWalletInit(
    network: network,
    dbpath: dbpath,
    descriptorStr: descriptorStr,
  );

  /// Get network of the wallet
  Network network();

  /// Sign a wallet transaction, returns pset
  Future<String> signTx({
    required Network network,
    required String pset,
    required String mnemonic,
  });

  /// Syncs the wallet db with its latest state fetched from the electrum server
  Future<void> sync_({required String electrumUrl});

  /// Get the transaction history of the wallet
  Future<List<Tx>> txs();
}
