#!/bin/bash

set -e

rustup target add aarch64-apple-ios
cargo build --release --target aarch64-apple-ios

# uniffi bindings
cargo run --bin uniffi-bindgen generate \
  --library ./target/aarch64-apple-ios/release/libmanna_core.dylib \
  --language swift \
  --out-dir ./NSEBindings

mv ./NSEBindings/manna_coreFFI.modulemap ./NSEBindings/module.modulemap

# This is cause Apple `thinks different` and require manna_core binary which is generated by dart build hook but, due to dependency graph, the NSE builds first and then hook runs,
# so after changing NSE rust code we have to build static libs and link it in xcode
rm -rf ../../../ios/NotificationExtension/NSE_Rust/MannaCore.xcframework
xcodebuild -create-xcframework \
  -library "./target/aarch64-apple-ios/release/libmanna_core.a" \
  -headers "./NSEBindings" \
  -output "../../../ios/NotificationExtension/NSE_Rust/MannaCore.xcframework"
cp ./NSEBindings/manna_core.swift ../../../ios/NotificationExtension/manna_core.swift
