#!/bin/bash

set -e

# This is cause Apple `thinks different` and require manna_core binary which is generated by dart build hook but, due to dependency graph, the NSE builds first and then hook runs,
# so after changing NSE rust code we have to build static libs and link it in xcode
rustup target add aarch64-apple-darwin x86_64-apple-darwin
cargo build --release --target aarch64-apple-darwin
cargo build --release --target x86_64-apple-darwin

lipo -create \
  ./target/aarch64-apple-darwin/release/libmanna_core.dylib \
  ./target/x86_64-apple-darwin/release/libmanna_core.dylib \
  -output ./target/universal-apple-darwin-dylib.dylib

lipo -create \
  ./target/aarch64-apple-darwin/release/libmanna_core.a \
  ./target/x86_64-apple-darwin/release/libmanna_core.a \
  -output ./target/universal-apple-darwin-static.a

cargo run --bin uniffi-bindgen generate \
  --library ./target/universal-apple-darwin-dylib.dylib \
  --language swift \
  --out-dir ./NSEBindingsMac

mv ./NSEBindingsMac/manna_coreFFI.modulemap ./NSEBindingsMac/module.modulemap

rm -rf ../../../macos/NotificationExtension/NSE_Rust/MannaCore.xcframework
xcodebuild -create-xcframework \
  -library "./target/universal-apple-darwin-static.a" \
  -headers "./NSEBindingsMac" \
  -output "../../../macos/NotificationExtension/NSE_Rust/MannaCore.xcframework"
cp ./NSEBindingsMac/manna_core.swift ../../../macos/NotificationExtension/manna_core.swift