// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'boltz/bolt12.dart';
import 'boltz/error.dart';
import 'boltz/swap_transaction.dart';
import 'boltz/types.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'util.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

class BoltzManager {
  final ApiConfig apiConfig;

  const BoltzManager({required this.apiConfig});

  /// accept on-chain swap quote
  Future<bool> acceptChainSwapQuote({
    required Swap swap,
    required BigInt quoteAmount,
  }) => MannaCore.instance.api.crateBoltzBoltzManagerAcceptChainSwapQuote(
    that: this,
    swap: swap,
    quoteAmount: quoteAmount,
  );

  /// Broadcast using boltz's electrum server
  Future<String> broadcastBoltz({
    required Chain chain,
    required Network network,
    required String signedHex,
  }) => MannaCore.instance.api.crateBoltzBoltzManagerBroadcastBoltz(
    that: this,
    chain: chain,
    network: network,
    signedHex: signedHex,
  );

  /// Broadcast tx using your own electrum server
  Future<String> broadcastElectrum({
    required Network network,
    required Chain chain,
    required String signedHex,
  }) => MannaCore.instance.api.crateBoltzBoltzManagerBroadcastElectrum(
    that: this,
    network: network,
    chain: chain,
    signedHex: signedHex,
  );

  /// broadcast signed tx hex to electrum server fallback to boltz for broadcasting, return txID.
  Future<String> broadcastSwapTx({
    required String txHex,
    required Network network,
    required Chain chain,
  }) => MannaCore.instance.api.crateBoltzBoltzManagerBroadcastSwapTx(
    that: this,
    txHex: txHex,
    network: network,
    chain: chain,
  );

  /// claim chain swap
  Future<String> claimChain({
    required Swap swap,
    required String claimAddress,
    required String serverClaimAddress,
    required TxFee minerFee,
    required bool tryCooperate,
  }) => MannaCore.instance.api.crateBoltzBoltzManagerClaimChain(
    that: this,
    swap: swap,
    claimAddress: claimAddress,
    serverClaimAddress: serverClaimAddress,
    minerFee: minerFee,
    tryCooperate: tryCooperate,
  );

  /// claim the reverse swap once its status is transaction.confirmed and boltz's lockup tx is
  /// included in the block the function doesn't check confirmation on lockup tx.
  Future<String> claimReverse({
    required Swap swap,
    required String claimAddress,
    required TxFee minerFee,
    required bool tryCooperate,
  }) => MannaCore.instance.api.crateBoltzBoltzManagerClaimReverse(
    that: this,
    swap: swap,
    claimAddress: claimAddress,
    minerFee: minerFee,
    tryCooperate: tryCooperate,
  );

  /// close the swap by letting boltz claim the locked up coins.
  Future<void> closeSubmarineCoop({required Swap swap}) => MannaCore
      .instance
      .api
      .crateBoltzBoltzManagerCloseSubmarineCoop(that: this, swap: swap);

  Future<(String, String)> createBol12Invoice({
    required String offerStr,
    required String invoiceRequestHex,
    required KeyPair signingKey,
    required Network network,
    required String preimageHash,
    required String liquidAddress,
  }) => MannaCore.instance.api.crateBoltzBoltzManagerCreateBol12Invoice(
    that: this,
    offerStr: offerStr,
    invoiceRequestHex: invoiceRequestHex,
    signingKey: signingKey,
    network: network,
    preimageHash: preimageHash,
    liquidAddress: liquidAddress,
  );

  Future<List<(LiquidWallet, String, KeyPair)>> createBolt12Offer({
    required Network network,
    required List<Bolt12OfferCreationParam> params,
  }) => MannaCore.instance.api.crateBoltzBoltzManagerCreateBolt12Offer(
    that: this,
    network: network,
    params: params,
  );

  /// returns (invoice, Magic routing hint bip21)
  Future<(String, String?)> generateBolt12InvoiceForSend({
    required Network network,
    required String offer,
    required BigInt amount,
    String? note,
  }) =>
      MannaCore.instance.api.crateBoltzBoltzManagerGenerateBolt12InvoiceForSend(
        that: this,
        network: network,
        offer: offer,
        amount: amount,
        note: note,
      );

  /// get on-chain swap negotiable value if locked up amount is not according to swap amount
  Future<BigInt> getChainSwapQuote({required Swap swap}) => MannaCore
      .instance
      .api
      .crateBoltzBoltzManagerGetChainSwapQuote(that: this, swap: swap);

  /// Chain swaps
  Future<Swap> newChain({
    required LiquidWallet wallet,
    required Network network,
    required ChainSwapDirection direction,
    required BigInt index,
    required BigInt amount,
    String? note,
    ExtraSwapFee? extraSwapFee,
    WebHook? webHook,
  }) => MannaCore.instance.api.crateBoltzBoltzManagerNewChain(
    that: this,
    wallet: wallet,
    network: network,
    direction: direction,
    index: index,
    amount: amount,
    note: note,
    extraSwapFee: extraSwapFee,
    webHook: webHook,
  );

  /// Reverse swap
  /// Lightning -> Chain,
  /// pass amount and note or bolt12_invoice,
  /// address signature is optional and defaults to schnorr signature with claim key, pass it in case of bolt12 signed by signing key
  Future<Swap> newReverse({
    required LiquidWallet wallet,
    required Network network,
    required Chain to,
    String? address,
    String? addressSignature,
    BigInt? amount,
    required BigInt index,
    String? note,
    ExtraSwapFee? extraSwapFee,
    WebHook? webHook,
    String? bolt12Invoice,
  }) => MannaCore.instance.api.crateBoltzBoltzManagerNewReverse(
    that: this,
    wallet: wallet,
    network: network,
    to: to,
    address: address,
    addressSignature: addressSignature,
    amount: amount,
    index: index,
    note: note,
    extraSwapFee: extraSwapFee,
    webHook: webHook,
    bolt12Invoice: bolt12Invoice,
  );

  /// Submarine swap
  /// Chain -> Lightning
  /// invoice is either bolt11 or bolt12 invoice
  Future<Swap> newSubmarine({
    required LiquidWallet wallet,
    required BigInt index,
    required Network network,
    required Chain from,
    required String invoice,
    String? note,
    ExtraSwapFee? extraSwapFee,
    WebHook? webHook,
  }) => MannaCore.instance.api.crateBoltzBoltzManagerNewSubmarine(
    that: this,
    wallet: wallet,
    index: index,
    network: network,
    from: from,
    invoice: invoice,
    note: note,
    extraSwapFee: extraSwapFee,
    webHook: webHook,
  );

  /// refund chain swap
  Future<String> refundChain({
    required Swap swap,
    required String refundAddress,
    required TxFee minerFee,
    required bool tryCooperate,
  }) => MannaCore.instance.api.crateBoltzBoltzManagerRefundChain(
    that: this,
    swap: swap,
    refundAddress: refundAddress,
    minerFee: minerFee,
    tryCooperate: tryCooperate,
  );

  /// if for some reason boltz fails to lockup funds or if the amount sent is not satisfactory.
  /// call the function to refund the locked up funds.
  /// returns refund transaction byte string
  Future<String> refundSubmarine({
    required Swap swap,
    required String refundAddress,
    required TxFee minerFee,
    required bool tryCooperate,
  }) => MannaCore.instance.api.crateBoltzBoltzManagerRefundSubmarine(
    that: this,
    swap: swap,
    refundAddress: refundAddress,
    minerFee: minerFee,
    tryCooperate: tryCooperate,
  );

  @override
  int get hashCode => apiConfig.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BoltzManager &&
          runtimeType == other.runtimeType &&
          apiConfig == other.apiConfig;
}
