// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'boltz.dart';
import 'boltz/bolt12.dart';
import 'boltz/error.dart';
import 'boltz/process_swap.dart';
import 'boltz/swap_transaction.dart';
import 'boltz/types.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'lib.dart';
import 'lnurl_util.dart';
import 'logger.dart';
import 'lwk/blockchain.dart';
import 'lwk/descriptor.dart';
import 'lwk/error.dart';
import 'lwk/types.dart';
import 'lwk/wallet.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'util.dart';

abstract class MannaCoreApiImplPlatform extends BaseApiImpl<MannaCoreWire> {
  MannaCoreApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_Bip32Ptr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32Ptr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_MasterSwapKeyPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKeyPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_WalletPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Bip32
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32(
    dynamic raw,
  );

  @protected
  MasterSwapKey
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKey(
    dynamic raw,
  );

  @protected
  Wallet
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
    dynamic raw,
  );

  @protected
  Bip32
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32(
    dynamic raw,
  );

  @protected
  MasterSwapKey
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKey(
    dynamic raw,
  );

  @protected
  Wallet
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
    dynamic raw,
  );

  @protected
  FutureOr<void> Function(Swap)
  dco_decode_DartFn_Inputs_swap_Output_unit_AnyhowException(dynamic raw);

  @protected
  Object dco_decode_DartOpaque(dynamic raw);

  @protected
  Bip32
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32(
    dynamic raw,
  );

  @protected
  MasterSwapKey
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKey(
    dynamic raw,
  );

  @protected
  Wallet
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BigInt dco_decode_U128(dynamic raw);

  @protected
  Address dco_decode_address(dynamic raw);

  @protected
  AddressEntry dco_decode_address_entry(dynamic raw);

  @protected
  ApiConfig dco_decode_api_config(dynamic raw);

  @protected
  Balance dco_decode_balance(dynamic raw);

  @protected
  Blockchain dco_decode_blockchain(dynamic raw);

  @protected
  Bolt12OfferCreationParam dco_decode_bolt_12_offer_creation_param(dynamic raw);

  @protected
  BoltzError dco_decode_boltz_error(dynamic raw);

  @protected
  BoltzManager dco_decode_boltz_manager(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AddressEntry dco_decode_box_autoadd_address_entry(dynamic raw);

  @protected
  ApiConfig dco_decode_box_autoadd_api_config(dynamic raw);

  @protected
  BoltzManager dco_decode_box_autoadd_boltz_manager(dynamic raw);

  @protected
  bool dco_decode_box_autoadd_bool(dynamic raw);

  @protected
  ChainSwap dco_decode_box_autoadd_chain_swap(dynamic raw);

  @protected
  ExtraSwapFee dco_decode_box_autoadd_extra_swap_fee(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  KeyPair dco_decode_box_autoadd_key_pair(dynamic raw);

  @protected
  LiquidWallet dco_decode_box_autoadd_liquid_wallet(dynamic raw);

  @protected
  (String, String) dco_decode_box_autoadd_record_string_string(dynamic raw);

  @protected
  (String, BigInt) dco_decode_box_autoadd_record_string_u_64(dynamic raw);

  @protected
  (Swap, bool?) dco_decode_box_autoadd_record_swap_opt_box_autoadd_bool(
    dynamic raw,
  );

  @protected
  ReverseSwap dco_decode_box_autoadd_reverse_swap(dynamic raw);

  @protected
  SubmarineSwap dco_decode_box_autoadd_submarine_swap(dynamic raw);

  @protected
  Swap dco_decode_box_autoadd_swap(dynamic raw);

  @protected
  Tx dco_decode_box_autoadd_tx(dynamic raw);

  @protected
  TxFee dco_decode_box_autoadd_tx_fee(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  WebHook dco_decode_box_autoadd_web_hook(dynamic raw);

  @protected
  Chain dco_decode_chain(dynamic raw);

  @protected
  ChainSwap dco_decode_chain_swap(dynamic raw);

  @protected
  ChainSwapData dco_decode_chain_swap_data(dynamic raw);

  @protected
  ChainSwapDirection dco_decode_chain_swap_direction(dynamic raw);

  @protected
  Crypto dco_decode_crypto(dynamic raw);

  @protected
  DecodedBolt12InvoiceRequest dco_decode_decoded_bolt_12_invoice_request(
    dynamic raw,
  );

  @protected
  DecodedBolt12Offer dco_decode_decoded_bolt_12_offer(dynamic raw);

  @protected
  DecodedInvoice dco_decode_decoded_invoice(dynamic raw);

  @protected
  DecodedPset dco_decode_decoded_pset(dynamic raw);

  @protected
  Descriptor dco_decode_descriptor(dynamic raw);

  @protected
  ExtraSwapFee dco_decode_extra_swap_fee(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  Fee dco_decode_fee(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_isize(dynamic raw);

  @protected
  KeyPair dco_decode_key_pair(dynamic raw);

  @protected
  LeafData dco_decode_leaf_data(dynamic raw);

  @protected
  LiquidWallet dco_decode_liquid_wallet(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Balance> dco_decode_list_balance(dynamic raw);

  @protected
  List<Bolt12OfferCreationParam> dco_decode_list_bolt_12_offer_creation_param(
    dynamic raw,
  );

  @protected
  List<Fee> dco_decode_list_fee(dynamic raw);

  @protected
  List<LiquidWallet> dco_decode_list_liquid_wallet(dynamic raw);

  @protected
  List<LnurlPoolEntry> dco_decode_list_lnurl_pool_entry(dynamic raw);

  @protected
  List<Network> dco_decode_list_network(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(LiquidWallet, String, KeyPair)>
  dco_decode_list_record_liquid_wallet_string_key_pair(dynamic raw);

  @protected
  List<(String, BigInt)> dco_decode_list_record_string_u_64(dynamic raw);

  @protected
  List<(BigInt, String)> dco_decode_list_record_u_64_string(dynamic raw);

  @protected
  List<Swap> dco_decode_list_swap(dynamic raw);

  @protected
  List<SwapTransaction> dco_decode_list_swap_transaction(dynamic raw);

  @protected
  List<Tx> dco_decode_list_tx(dynamic raw);

  @protected
  List<TxOut> dco_decode_list_tx_out(dynamic raw);

  @protected
  LnurlPoolEntry dco_decode_lnurl_pool_entry(dynamic raw);

  @protected
  LnurlUtil dco_decode_lnurl_util(dynamic raw);

  @protected
  LwkError dco_decode_lwk_error(dynamic raw);

  @protected
  MannaError dco_decode_manna_error(dynamic raw);

  @protected
  Mnemonics dco_decode_mnemonics(dynamic raw);

  @protected
  Network dco_decode_network(dynamic raw);

  @protected
  NetworkConfig dco_decode_network_config(dynamic raw);

  @protected
  NetworkEndpoints dco_decode_network_endpoints(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BigInt? dco_decode_opt_U128(dynamic raw);

  @protected
  AddressEntry? dco_decode_opt_box_autoadd_address_entry(dynamic raw);

  @protected
  bool? dco_decode_opt_box_autoadd_bool(dynamic raw);

  @protected
  ChainSwap? dco_decode_opt_box_autoadd_chain_swap(dynamic raw);

  @protected
  ExtraSwapFee? dco_decode_opt_box_autoadd_extra_swap_fee(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  KeyPair? dco_decode_opt_box_autoadd_key_pair(dynamic raw);

  @protected
  (String, String)? dco_decode_opt_box_autoadd_record_string_string(
    dynamic raw,
  );

  @protected
  (String, BigInt)? dco_decode_opt_box_autoadd_record_string_u_64(dynamic raw);

  @protected
  (Swap, bool?)? dco_decode_opt_box_autoadd_record_swap_opt_box_autoadd_bool(
    dynamic raw,
  );

  @protected
  ReverseSwap? dco_decode_opt_box_autoadd_reverse_swap(dynamic raw);

  @protected
  SubmarineSwap? dco_decode_opt_box_autoadd_submarine_swap(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  WebHook? dco_decode_opt_box_autoadd_web_hook(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  List<(BigInt, String)>? dco_decode_opt_list_record_u_64_string(dynamic raw);

  @protected
  U8Array32? dco_decode_opt_u_8_array_32(dynamic raw);

  @protected
  OutPoint dco_decode_out_point(dynamic raw);

  @protected
  PreImage dco_decode_pre_image(dynamic raw);

  @protected
  (LiquidWallet, String, KeyPair)
  dco_decode_record_liquid_wallet_string_key_pair(dynamic raw);

  @protected
  (String, String?) dco_decode_record_string_opt_string(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  (String, BigInt) dco_decode_record_string_u_64(dynamic raw);

  @protected
  (Swap, bool) dco_decode_record_swap_bool(dynamic raw);

  @protected
  (Swap, bool?) dco_decode_record_swap_opt_box_autoadd_bool(dynamic raw);

  @protected
  (BigInt, String) dco_decode_record_u_64_string(dynamic raw);

  @protected
  ReverseResponse dco_decode_reverse_response(dynamic raw);

  @protected
  ReverseSwap dco_decode_reverse_swap(dynamic raw);

  @protected
  SubmarineResponse dco_decode_submarine_response(dynamic raw);

  @protected
  SubmarineSwap dco_decode_submarine_swap(dynamic raw);

  @protected
  SupabaseConfig dco_decode_supabase_config(dynamic raw);

  @protected
  Swap dco_decode_swap(dynamic raw);

  @protected
  SwapTransaction dco_decode_swap_transaction(dynamic raw);

  @protected
  SwapTransactionType dco_decode_swap_transaction_type(dynamic raw);

  @protected
  SwapTreeData dco_decode_swap_tree_data(dynamic raw);

  @protected
  Tx dco_decode_tx(dynamic raw);

  @protected
  TxFee dco_decode_tx_fee(dynamic raw);

  @protected
  TxOut dco_decode_tx_out(dynamic raw);

  @protected
  TxOutSecrets dco_decode_tx_out_secrets(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  U8Array32 dco_decode_u_8_array_32(dynamic raw);

  @protected
  U8Array33 dco_decode_u_8_array_33(dynamic raw);

  @protected
  U8Array64 dco_decode_u_8_array_64(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WalletType dco_decode_wallet_type(dynamic raw);

  @protected
  WebHook dco_decode_web_hook(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Bip32
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32(
    SseDeserializer deserializer,
  );

  @protected
  MasterSwapKey
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKey(
    SseDeserializer deserializer,
  );

  @protected
  Wallet
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
    SseDeserializer deserializer,
  );

  @protected
  Bip32
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32(
    SseDeserializer deserializer,
  );

  @protected
  MasterSwapKey
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKey(
    SseDeserializer deserializer,
  );

  @protected
  Wallet
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
    SseDeserializer deserializer,
  );

  @protected
  Object sse_decode_DartOpaque(SseDeserializer deserializer);

  @protected
  Bip32
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32(
    SseDeserializer deserializer,
  );

  @protected
  MasterSwapKey
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKey(
    SseDeserializer deserializer,
  );

  @protected
  Wallet
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_U128(SseDeserializer deserializer);

  @protected
  Address sse_decode_address(SseDeserializer deserializer);

  @protected
  AddressEntry sse_decode_address_entry(SseDeserializer deserializer);

  @protected
  ApiConfig sse_decode_api_config(SseDeserializer deserializer);

  @protected
  Balance sse_decode_balance(SseDeserializer deserializer);

  @protected
  Blockchain sse_decode_blockchain(SseDeserializer deserializer);

  @protected
  Bolt12OfferCreationParam sse_decode_bolt_12_offer_creation_param(
    SseDeserializer deserializer,
  );

  @protected
  BoltzError sse_decode_boltz_error(SseDeserializer deserializer);

  @protected
  BoltzManager sse_decode_boltz_manager(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AddressEntry sse_decode_box_autoadd_address_entry(
    SseDeserializer deserializer,
  );

  @protected
  ApiConfig sse_decode_box_autoadd_api_config(SseDeserializer deserializer);

  @protected
  BoltzManager sse_decode_box_autoadd_boltz_manager(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ChainSwap sse_decode_box_autoadd_chain_swap(SseDeserializer deserializer);

  @protected
  ExtraSwapFee sse_decode_box_autoadd_extra_swap_fee(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  KeyPair sse_decode_box_autoadd_key_pair(SseDeserializer deserializer);

  @protected
  LiquidWallet sse_decode_box_autoadd_liquid_wallet(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_box_autoadd_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  (String, BigInt) sse_decode_box_autoadd_record_string_u_64(
    SseDeserializer deserializer,
  );

  @protected
  (Swap, bool?) sse_decode_box_autoadd_record_swap_opt_box_autoadd_bool(
    SseDeserializer deserializer,
  );

  @protected
  ReverseSwap sse_decode_box_autoadd_reverse_swap(SseDeserializer deserializer);

  @protected
  SubmarineSwap sse_decode_box_autoadd_submarine_swap(
    SseDeserializer deserializer,
  );

  @protected
  Swap sse_decode_box_autoadd_swap(SseDeserializer deserializer);

  @protected
  Tx sse_decode_box_autoadd_tx(SseDeserializer deserializer);

  @protected
  TxFee sse_decode_box_autoadd_tx_fee(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  WebHook sse_decode_box_autoadd_web_hook(SseDeserializer deserializer);

  @protected
  Chain sse_decode_chain(SseDeserializer deserializer);

  @protected
  ChainSwap sse_decode_chain_swap(SseDeserializer deserializer);

  @protected
  ChainSwapData sse_decode_chain_swap_data(SseDeserializer deserializer);

  @protected
  ChainSwapDirection sse_decode_chain_swap_direction(
    SseDeserializer deserializer,
  );

  @protected
  Crypto sse_decode_crypto(SseDeserializer deserializer);

  @protected
  DecodedBolt12InvoiceRequest sse_decode_decoded_bolt_12_invoice_request(
    SseDeserializer deserializer,
  );

  @protected
  DecodedBolt12Offer sse_decode_decoded_bolt_12_offer(
    SseDeserializer deserializer,
  );

  @protected
  DecodedInvoice sse_decode_decoded_invoice(SseDeserializer deserializer);

  @protected
  DecodedPset sse_decode_decoded_pset(SseDeserializer deserializer);

  @protected
  Descriptor sse_decode_descriptor(SseDeserializer deserializer);

  @protected
  ExtraSwapFee sse_decode_extra_swap_fee(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  Fee sse_decode_fee(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_isize(SseDeserializer deserializer);

  @protected
  KeyPair sse_decode_key_pair(SseDeserializer deserializer);

  @protected
  LeafData sse_decode_leaf_data(SseDeserializer deserializer);

  @protected
  LiquidWallet sse_decode_liquid_wallet(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Balance> sse_decode_list_balance(SseDeserializer deserializer);

  @protected
  List<Bolt12OfferCreationParam> sse_decode_list_bolt_12_offer_creation_param(
    SseDeserializer deserializer,
  );

  @protected
  List<Fee> sse_decode_list_fee(SseDeserializer deserializer);

  @protected
  List<LiquidWallet> sse_decode_list_liquid_wallet(
    SseDeserializer deserializer,
  );

  @protected
  List<LnurlPoolEntry> sse_decode_list_lnurl_pool_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<Network> sse_decode_list_network(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(LiquidWallet, String, KeyPair)>
  sse_decode_list_record_liquid_wallet_string_key_pair(
    SseDeserializer deserializer,
  );

  @protected
  List<(String, BigInt)> sse_decode_list_record_string_u_64(
    SseDeserializer deserializer,
  );

  @protected
  List<(BigInt, String)> sse_decode_list_record_u_64_string(
    SseDeserializer deserializer,
  );

  @protected
  List<Swap> sse_decode_list_swap(SseDeserializer deserializer);

  @protected
  List<SwapTransaction> sse_decode_list_swap_transaction(
    SseDeserializer deserializer,
  );

  @protected
  List<Tx> sse_decode_list_tx(SseDeserializer deserializer);

  @protected
  List<TxOut> sse_decode_list_tx_out(SseDeserializer deserializer);

  @protected
  LnurlPoolEntry sse_decode_lnurl_pool_entry(SseDeserializer deserializer);

  @protected
  LnurlUtil sse_decode_lnurl_util(SseDeserializer deserializer);

  @protected
  LwkError sse_decode_lwk_error(SseDeserializer deserializer);

  @protected
  MannaError sse_decode_manna_error(SseDeserializer deserializer);

  @protected
  Mnemonics sse_decode_mnemonics(SseDeserializer deserializer);

  @protected
  Network sse_decode_network(SseDeserializer deserializer);

  @protected
  NetworkConfig sse_decode_network_config(SseDeserializer deserializer);

  @protected
  NetworkEndpoints sse_decode_network_endpoints(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_U128(SseDeserializer deserializer);

  @protected
  AddressEntry? sse_decode_opt_box_autoadd_address_entry(
    SseDeserializer deserializer,
  );

  @protected
  bool? sse_decode_opt_box_autoadd_bool(SseDeserializer deserializer);

  @protected
  ChainSwap? sse_decode_opt_box_autoadd_chain_swap(
    SseDeserializer deserializer,
  );

  @protected
  ExtraSwapFee? sse_decode_opt_box_autoadd_extra_swap_fee(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  KeyPair? sse_decode_opt_box_autoadd_key_pair(SseDeserializer deserializer);

  @protected
  (String, String)? sse_decode_opt_box_autoadd_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  (String, BigInt)? sse_decode_opt_box_autoadd_record_string_u_64(
    SseDeserializer deserializer,
  );

  @protected
  (Swap, bool?)? sse_decode_opt_box_autoadd_record_swap_opt_box_autoadd_bool(
    SseDeserializer deserializer,
  );

  @protected
  ReverseSwap? sse_decode_opt_box_autoadd_reverse_swap(
    SseDeserializer deserializer,
  );

  @protected
  SubmarineSwap? sse_decode_opt_box_autoadd_submarine_swap(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  WebHook? sse_decode_opt_box_autoadd_web_hook(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  List<(BigInt, String)>? sse_decode_opt_list_record_u_64_string(
    SseDeserializer deserializer,
  );

  @protected
  U8Array32? sse_decode_opt_u_8_array_32(SseDeserializer deserializer);

  @protected
  OutPoint sse_decode_out_point(SseDeserializer deserializer);

  @protected
  PreImage sse_decode_pre_image(SseDeserializer deserializer);

  @protected
  (LiquidWallet, String, KeyPair)
  sse_decode_record_liquid_wallet_string_key_pair(SseDeserializer deserializer);

  @protected
  (String, String?) sse_decode_record_string_opt_string(
    SseDeserializer deserializer,
  );

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  (String, BigInt) sse_decode_record_string_u_64(SseDeserializer deserializer);

  @protected
  (Swap, bool) sse_decode_record_swap_bool(SseDeserializer deserializer);

  @protected
  (Swap, bool?) sse_decode_record_swap_opt_box_autoadd_bool(
    SseDeserializer deserializer,
  );

  @protected
  (BigInt, String) sse_decode_record_u_64_string(SseDeserializer deserializer);

  @protected
  ReverseResponse sse_decode_reverse_response(SseDeserializer deserializer);

  @protected
  ReverseSwap sse_decode_reverse_swap(SseDeserializer deserializer);

  @protected
  SubmarineResponse sse_decode_submarine_response(SseDeserializer deserializer);

  @protected
  SubmarineSwap sse_decode_submarine_swap(SseDeserializer deserializer);

  @protected
  SupabaseConfig sse_decode_supabase_config(SseDeserializer deserializer);

  @protected
  Swap sse_decode_swap(SseDeserializer deserializer);

  @protected
  SwapTransaction sse_decode_swap_transaction(SseDeserializer deserializer);

  @protected
  SwapTransactionType sse_decode_swap_transaction_type(
    SseDeserializer deserializer,
  );

  @protected
  SwapTreeData sse_decode_swap_tree_data(SseDeserializer deserializer);

  @protected
  Tx sse_decode_tx(SseDeserializer deserializer);

  @protected
  TxFee sse_decode_tx_fee(SseDeserializer deserializer);

  @protected
  TxOut sse_decode_tx_out(SseDeserializer deserializer);

  @protected
  TxOutSecrets sse_decode_tx_out_secrets(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  U8Array32 sse_decode_u_8_array_32(SseDeserializer deserializer);

  @protected
  U8Array33 sse_decode_u_8_array_33(SseDeserializer deserializer);

  @protected
  U8Array64 sse_decode_u_8_array_64(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WalletType sse_decode_wallet_type(SseDeserializer deserializer);

  @protected
  WebHook sse_decode_web_hook(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32(
    Bip32 self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKey(
    MasterSwapKey self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
    Wallet self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32(
    Bip32 self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKey(
    MasterSwapKey self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
    Wallet self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartFn_Inputs_swap_Output_unit_AnyhowException(
    FutureOr<void> Function(Swap) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_DartOpaque(Object self, SseSerializer serializer);

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32(
    Bip32 self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKey(
    MasterSwapKey self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
    Wallet self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_U128(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_address(Address self, SseSerializer serializer);

  @protected
  void sse_encode_address_entry(AddressEntry self, SseSerializer serializer);

  @protected
  void sse_encode_api_config(ApiConfig self, SseSerializer serializer);

  @protected
  void sse_encode_balance(Balance self, SseSerializer serializer);

  @protected
  void sse_encode_blockchain(Blockchain self, SseSerializer serializer);

  @protected
  void sse_encode_bolt_12_offer_creation_param(
    Bolt12OfferCreationParam self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_boltz_error(BoltzError self, SseSerializer serializer);

  @protected
  void sse_encode_boltz_manager(BoltzManager self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_address_entry(
    AddressEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_config(
    ApiConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_boltz_manager(
    BoltzManager self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_chain_swap(
    ChainSwap self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_extra_swap_fee(
    ExtraSwapFee self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_key_pair(KeyPair self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_liquid_wallet(
    LiquidWallet self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_record_string_u_64(
    (String, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_record_swap_opt_box_autoadd_bool(
    (Swap, bool?) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_reverse_swap(
    ReverseSwap self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_submarine_swap(
    SubmarineSwap self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_swap(Swap self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_tx(Tx self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_tx_fee(TxFee self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_web_hook(WebHook self, SseSerializer serializer);

  @protected
  void sse_encode_chain(Chain self, SseSerializer serializer);

  @protected
  void sse_encode_chain_swap(ChainSwap self, SseSerializer serializer);

  @protected
  void sse_encode_chain_swap_data(ChainSwapData self, SseSerializer serializer);

  @protected
  void sse_encode_chain_swap_direction(
    ChainSwapDirection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_crypto(Crypto self, SseSerializer serializer);

  @protected
  void sse_encode_decoded_bolt_12_invoice_request(
    DecodedBolt12InvoiceRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_decoded_bolt_12_offer(
    DecodedBolt12Offer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_decoded_invoice(
    DecodedInvoice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_decoded_pset(DecodedPset self, SseSerializer serializer);

  @protected
  void sse_encode_descriptor(Descriptor self, SseSerializer serializer);

  @protected
  void sse_encode_extra_swap_fee(ExtraSwapFee self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_fee(Fee self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_isize(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_key_pair(KeyPair self, SseSerializer serializer);

  @protected
  void sse_encode_leaf_data(LeafData self, SseSerializer serializer);

  @protected
  void sse_encode_liquid_wallet(LiquidWallet self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_balance(List<Balance> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bolt_12_offer_creation_param(
    List<Bolt12OfferCreationParam> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_fee(List<Fee> self, SseSerializer serializer);

  @protected
  void sse_encode_list_liquid_wallet(
    List<LiquidWallet> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_lnurl_pool_entry(
    List<LnurlPoolEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_network(List<Network> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_liquid_wallet_string_key_pair(
    List<(LiquidWallet, String, KeyPair)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_u_64(
    List<(String, BigInt)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_u_64_string(
    List<(BigInt, String)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_swap(List<Swap> self, SseSerializer serializer);

  @protected
  void sse_encode_list_swap_transaction(
    List<SwapTransaction> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_tx(List<Tx> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tx_out(List<TxOut> self, SseSerializer serializer);

  @protected
  void sse_encode_lnurl_pool_entry(
    LnurlPoolEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_lnurl_util(LnurlUtil self, SseSerializer serializer);

  @protected
  void sse_encode_lwk_error(LwkError self, SseSerializer serializer);

  @protected
  void sse_encode_manna_error(MannaError self, SseSerializer serializer);

  @protected
  void sse_encode_mnemonics(Mnemonics self, SseSerializer serializer);

  @protected
  void sse_encode_network(Network self, SseSerializer serializer);

  @protected
  void sse_encode_network_config(NetworkConfig self, SseSerializer serializer);

  @protected
  void sse_encode_network_endpoints(
    NetworkEndpoints self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_U128(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_address_entry(
    AddressEntry? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bool(bool? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_chain_swap(
    ChainSwap? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_extra_swap_fee(
    ExtraSwapFee? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_key_pair(
    KeyPair? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_record_string_string(
    (String, String)? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_record_string_u_64(
    (String, BigInt)? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_record_swap_opt_box_autoadd_bool(
    (Swap, bool?)? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_reverse_swap(
    ReverseSwap? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_submarine_swap(
    SubmarineSwap? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_web_hook(
    WebHook? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_record_u_64_string(
    List<(BigInt, String)>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_u_8_array_32(U8Array32? self, SseSerializer serializer);

  @protected
  void sse_encode_out_point(OutPoint self, SseSerializer serializer);

  @protected
  void sse_encode_pre_image(PreImage self, SseSerializer serializer);

  @protected
  void sse_encode_record_liquid_wallet_string_key_pair(
    (LiquidWallet, String, KeyPair) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_opt_string(
    (String, String?) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_u_64(
    (String, BigInt) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_swap_bool((Swap, bool) self, SseSerializer serializer);

  @protected
  void sse_encode_record_swap_opt_box_autoadd_bool(
    (Swap, bool?) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_u_64_string(
    (BigInt, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reverse_response(
    ReverseResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_reverse_swap(ReverseSwap self, SseSerializer serializer);

  @protected
  void sse_encode_submarine_response(
    SubmarineResponse self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_submarine_swap(SubmarineSwap self, SseSerializer serializer);

  @protected
  void sse_encode_supabase_config(
    SupabaseConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_swap(Swap self, SseSerializer serializer);

  @protected
  void sse_encode_swap_transaction(
    SwapTransaction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_swap_transaction_type(
    SwapTransactionType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_swap_tree_data(SwapTreeData self, SseSerializer serializer);

  @protected
  void sse_encode_tx(Tx self, SseSerializer serializer);

  @protected
  void sse_encode_tx_fee(TxFee self, SseSerializer serializer);

  @protected
  void sse_encode_tx_out(TxOut self, SseSerializer serializer);

  @protected
  void sse_encode_tx_out_secrets(TxOutSecrets self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8_array_32(U8Array32 self, SseSerializer serializer);

  @protected
  void sse_encode_u_8_array_33(U8Array33 self, SseSerializer serializer);

  @protected
  void sse_encode_u_8_array_64(U8Array64 self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_type(WalletType self, SseSerializer serializer);

  @protected
  void sse_encode_web_hook(WebHook self, SseSerializer serializer);
}

// Section: wire_class

class MannaCoreWire implements BaseWire {
  factory MannaCoreWire.fromExternalLibrary(ExternalLibrary lib) =>
      MannaCoreWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  MannaCoreWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32Ptr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_manna_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32 =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32Ptr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32Ptr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_manna_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32 =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBIP32Ptr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKey(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKey(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKeyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_manna_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKey',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKey =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKeyPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKey(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKey(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKeyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_manna_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKey',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKey =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMasterSwapKeyPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_manna_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_manna_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWallet =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerWalletPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
