// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'boltz/swap_transaction.dart';
import 'boltz/types.dart';
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'util.dart';

class LnurlUtil {
  const LnurlUtil();

  /// parses lnurl URI or bech32 string to URI
  static String decode({required String lnurl}) =>
      MannaCore.instance.api.crateLnurlUtilLnurlUtilDecode(lnurl: lnurl);

  /// fetches pending lnurl swaps from database and returns it after decryption
  static Future<List<Swap>> fetchLnurlSwaps({
    required List<LiquidWallet> liquidWallets,
    required Network network,
    required ApiConfig apiConfig,
    required String jwtToken,
    required String deviceId,
  }) => MannaCore.instance.api.crateLnurlUtilLnurlUtilFetchLnurlSwaps(
    liquidWallets: liquidWallets,
    network: network,
    apiConfig: apiConfig,
    jwtToken: jwtToken,
    deviceId: deviceId,
  );

  static Future<String> getSigningDerivationPath({
    required U8Array32 hashingKey,
    required String lnurl,
  }) => MannaCore.instance.api.crateLnurlUtilLnurlUtilGetSigningDerivationPath(
    hashingKey: hashingKey,
    lnurl: lnurl,
  );

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LnurlUtil && runtimeType == other.runtimeType;
}
