// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'util.dart';

// These functions are ignored because they are not marked as `pub`: `get_config`, `get_server_api_endpoint`, `get_supabase_config`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `hash`

class ApiConfig {
  final NetworkConfig mainnet;
  final NetworkConfig testnet;
  final NetworkConfig regtest;

  const ApiConfig({
    required this.mainnet,
    required this.testnet,
    required this.regtest,
  });

  static ApiConfig fromJson({required String json}) =>
      MannaCore.instance.api.crateTypesApiConfigFromJson(json: json);

  String toJson() =>
      MannaCore.instance.api.crateTypesApiConfigToJson(that: this);

  @override
  int get hashCode => mainnet.hashCode ^ testnet.hashCode ^ regtest.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiConfig &&
          runtimeType == other.runtimeType &&
          mainnet == other.mainnet &&
          testnet == other.testnet &&
          regtest == other.regtest;
}

class DecodedBolt12Offer {
  final String id;
  final String parsedOffer;
  final bool isExpired;
  final List<Network> networks;
  final BigInt? amount;
  final String? description;
  final String? issuer;

  const DecodedBolt12Offer({
    required this.id,
    required this.parsedOffer,
    required this.isExpired,
    required this.networks,
    this.amount,
    this.description,
    this.issuer,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      parsedOffer.hashCode ^
      isExpired.hashCode ^
      networks.hashCode ^
      amount.hashCode ^
      description.hashCode ^
      issuer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedBolt12Offer &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          parsedOffer == other.parsedOffer &&
          isExpired == other.isExpired &&
          networks == other.networks &&
          amount == other.amount &&
          description == other.description &&
          issuer == other.issuer;
}

class DecodedInvoice {
  final BigInt msats;
  final BigInt expiresAt;
  final bool isExpired;
  final Network network;
  final (String, BigInt)? bip21;
  final String preimageHash;
  final String? description;

  /// bolt12 offer issuer
  final String? issuer;

  const DecodedInvoice({
    required this.msats,
    required this.expiresAt,
    required this.isExpired,
    required this.network,
    this.bip21,
    required this.preimageHash,
    this.description,
    this.issuer,
  });

  @override
  int get hashCode =>
      msats.hashCode ^
      expiresAt.hashCode ^
      isExpired.hashCode ^
      network.hashCode ^
      bip21.hashCode ^
      preimageHash.hashCode ^
      description.hashCode ^
      issuer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DecodedInvoice &&
          runtimeType == other.runtimeType &&
          msats == other.msats &&
          expiresAt == other.expiresAt &&
          isExpired == other.isExpired &&
          network == other.network &&
          bip21 == other.bip21 &&
          preimageHash == other.preimageHash &&
          description == other.description &&
          issuer == other.issuer;
}

class LiquidWallet {
  final String uuid;
  final WalletType walletType;
  final String? upsertDerivationPrivateKeyHex;
  final String? walletName;

  const LiquidWallet({
    required this.uuid,
    required this.walletType,
    this.upsertDerivationPrivateKeyHex,
    this.walletName,
  });

  @override
  int get hashCode =>
      uuid.hashCode ^
      walletType.hashCode ^
      upsertDerivationPrivateKeyHex.hashCode ^
      walletName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LiquidWallet &&
          runtimeType == other.runtimeType &&
          uuid == other.uuid &&
          walletType == other.walletType &&
          upsertDerivationPrivateKeyHex ==
              other.upsertDerivationPrivateKeyHex &&
          walletName == other.walletName;
}

enum Network { mainnet, testnet, regtest }

class NetworkConfig {
  final NetworkEndpoints bitcoin;
  final NetworkEndpoints liquid;
  final String boltzUrl;
  final BigInt boltzFeeCacheTimeoutMs;
  final SupabaseConfig supabase;
  final String serverUrl;
  final String serverApiVersion;

  const NetworkConfig({
    required this.bitcoin,
    required this.liquid,
    required this.boltzUrl,
    required this.boltzFeeCacheTimeoutMs,
    required this.supabase,
    required this.serverUrl,
    required this.serverApiVersion,
  });

  @override
  int get hashCode =>
      bitcoin.hashCode ^
      liquid.hashCode ^
      boltzUrl.hashCode ^
      boltzFeeCacheTimeoutMs.hashCode ^
      supabase.hashCode ^
      serverUrl.hashCode ^
      serverApiVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkConfig &&
          runtimeType == other.runtimeType &&
          bitcoin == other.bitcoin &&
          liquid == other.liquid &&
          boltzUrl == other.boltzUrl &&
          boltzFeeCacheTimeoutMs == other.boltzFeeCacheTimeoutMs &&
          supabase == other.supabase &&
          serverUrl == other.serverUrl &&
          serverApiVersion == other.serverApiVersion;
}

class NetworkEndpoints {
  final String esplora;
  final String electrum;

  const NetworkEndpoints({required this.esplora, required this.electrum});

  @override
  int get hashCode => esplora.hashCode ^ electrum.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NetworkEndpoints &&
          runtimeType == other.runtimeType &&
          esplora == other.esplora &&
          electrum == other.electrum;
}

class SupabaseConfig {
  final String projectRef;
  final String apiKey;

  const SupabaseConfig({required this.projectRef, required this.apiKey});

  @override
  int get hashCode => projectRef.hashCode ^ apiKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SupabaseConfig &&
          runtimeType == other.runtimeType &&
          projectRef == other.projectRef &&
          apiKey == other.apiKey;
}

enum WalletType { full }
