// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `decode_proto`, `encode_proto`, `vec_to_array`, `with_lock`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `LockedFileStore`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `get`, `is_persisted`, `put`, `remove`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `get_minimal_runtime`, `parse_bolt12_invoice`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `new`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BIP32>>
abstract class Bip32 implements RustOpaqueInterface {
  Bip32 derivePath({required String path});

  static Future<Bip32> fromMnemonics({
    required String mnemonic,
    String? password,
  }) => MannaCore.instance.api.crateUtilBip32FromMnemonics(
    mnemonic: mnemonic,
    password: password,
  );

  static Future<Bip32> fromSeed({required U8Array64 seed}) =>
      MannaCore.instance.api.crateUtilBip32FromSeed(seed: seed);

  static Future<Bip32> fromXpub({required String xpubStr}) =>
      MannaCore.instance.api.crateUtilBip32FromXpub(xpubStr: xpubStr);

  KeyPair? getKeyPair();

  U8Array32? getPrivateKey();

  /// returns public key bytes
  U8Array33 getPubKey();

  /// returns pubkeyhash (pubkey->sha-256->RIPEMD-160)
  String getPubKeyHashHex();

  String? getXprv();

  String getXpub();

  bool isWatchOnly();
}

class Crypto {
  const Crypto();

  /// pass nonce (12 bytes) + cipher + mac (16 bytes)
  static Future<Uint8List> aesDecrypt({
    required U8Array32 key,
    required List<int> payload,
    String? aad,
  }) => MannaCore.instance.api.crateUtilCryptoAesDecrypt(
    key: key,
    payload: payload,
    aad: aad,
  );

  /// returns nonce (12 bytes) + cipher + mac (16 bytes)
  static Future<Uint8List> aesEncrypt({
    required U8Array32 key,
    required List<int> plaintext,
    String? aad,
  }) => MannaCore.instance.api.crateUtilCryptoAesEncrypt(
    key: key,
    plaintext: plaintext,
    aad: aad,
  );

  /// parses bolt11 invoice, if you want to extract bip21 address used to create this lightning invoice use [Self::from_bolt11_invoice] instead.
  static DecodedInvoice decodeBolt11Invoice({required String invoice}) =>
      MannaCore.instance.api.crateUtilCryptoDecodeBolt11Invoice(
        invoice: invoice,
      );

  static DecodedInvoice decodeBolt12Invoice({required String invoice}) =>
      MannaCore.instance.api.crateUtilCryptoDecodeBolt12Invoice(
        invoice: invoice,
      );

  /// function to validate bolt12 lightning offer
  static Future<DecodedBolt12Offer> decodeBolt12Offer({
    required String offer,
  }) => MannaCore.instance.api.crateUtilCryptoDecodeBolt12Offer(offer: offer);

  /// Decodes spark address into identity pub key
  static (String, Network) decodeSparkAddress({required String addr}) =>
      MannaCore.instance.api.crateUtilCryptoDecodeSparkAddress(addr: addr);

  static Future<String> decryptChatMessageAsReceiver({
    required List<int> receiverPrivKey,
    required List<int> senderPubKey,
    required List<int> payload,
  }) => MannaCore.instance.api.crateUtilCryptoDecryptChatMessageAsReceiver(
    receiverPrivKey: receiverPrivKey,
    senderPubKey: senderPubKey,
    payload: payload,
  );

  static Future<String> decryptChatMessageAsSender({
    required List<int> senderPrivKey,
    required List<int> payload,
  }) => MannaCore.instance.api.crateUtilCryptoDecryptChatMessageAsSender(
    senderPrivKey: senderPrivKey,
    payload: payload,
  );

  static Future<Uint8List> decryptEcies({
    required List<int> privKey,
    required List<int> payload,
  }) => MannaCore.instance.api.crateUtilCryptoDecryptEcies(
    privKey: privKey,
    payload: payload,
  );

  static Future<U8Array32> deriveHkdf({
    required List<int> seed,
    required String info,
  }) =>
      MannaCore.instance.api.crateUtilCryptoDeriveHkdf(seed: seed, info: info);

  static Future<U8Array32> deriveX25519SharedSecret({
    required U8Array32 privateKeyBytes,
    required U8Array32 publicKeyBytes,
  }) => MannaCore.instance.api.crateUtilCryptoDeriveX25519SharedSecret(
    privateKeyBytes: privateKeyBytes,
    publicKeyBytes: publicKeyBytes,
  );

  /// Encodes spark identity pub key into spark address
  static String encodeSparkAddress({
    required String identityPubKeyHex,
    required Network network,
  }) => MannaCore.instance.api.crateUtilCryptoEncodeSparkAddress(
    identityPubKeyHex: identityPubKeyHex,
    network: network,
  );

  static Future<Uint8List> encryptChatMessage({
    required List<int> senderPrivKey,
    required List<int> receiverPubKey,
    required String message,
  }) => MannaCore.instance.api.crateUtilCryptoEncryptChatMessage(
    senderPrivKey: senderPrivKey,
    receiverPubKey: receiverPubKey,
    message: message,
  );

  static Future<Uint8List> encryptEcies({
    required List<int> pubKey,
    required List<int> payload,
  }) => MannaCore.instance.api.crateUtilCryptoEncryptEcies(
    pubKey: pubKey,
    payload: payload,
  );

  /// function to fetch bolt12 lightning offer for a given username using DNS query according to BIP-353
  static Future<String?> fetchBolt12OfferUriFromUsername({
    required Network network,
    required String username,
  }) => MannaCore.instance.api.crateUtilCryptoFetchBolt12OfferUriFromUsername(
    network: network,
    username: username,
  );

  static Future<KeyPair> generateX25519KeyPair({
    required U8Array32 privateKeyBytes,
  }) => MannaCore.instance.api.crateUtilCryptoGenerateX25519KeyPair(
    privateKeyBytes: privateKeyBytes,
  );

  static Future<KeyPair?> getSwapEncryptionKey({
    required String swapMnemonic,
  }) => MannaCore.instance.api.crateUtilCryptoGetSwapEncryptionKey(
    swapMnemonic: swapMnemonic,
  );

  static Future<Uint8List> secp256K1Sign({
    required List<int> privKey,
    required List<int> message,
    required bool returnDer,
    bool? preHash,
  }) => MannaCore.instance.api.crateUtilCryptoSecp256K1Sign(
    privKey: privKey,
    message: message,
    returnDer: returnDer,
    preHash: preHash,
  );

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Crypto && runtimeType == other.runtimeType;
}

class KeyPair {
  final Uint8List secretKey;
  final Uint8List publicKey;

  const KeyPair({required this.secretKey, required this.publicKey});

  @override
  int get hashCode => secretKey.hashCode ^ publicKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyPair &&
          runtimeType == other.runtimeType &&
          secretKey == other.secretKey &&
          publicKey == other.publicKey;
}

class MannaError implements FrbException {
  final String? kind;
  final String msg;

  const MannaError({this.kind, required this.msg});

  static Future<MannaError> from({
    required String kind,
    required String message,
  }) => MannaCore.instance.api.crateUtilMannaErrorFrom(
    kind: kind,
    message: message,
  );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<MannaError> newInstance({required String message}) =>
      MannaCore.instance.api.crateUtilMannaErrorNew(message: message);

  @override
  int get hashCode => kind.hashCode ^ msg.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MannaError &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          msg == other.msg;
}

class Mnemonics {
  final String sentence;
  final Uint8List entropy;
  final U8Array64 seedBytes;

  const Mnemonics({
    required this.sentence,
    required this.entropy,
    required this.seedBytes,
  });

  static Future<Mnemonics> generate({BigInt? wordCount}) =>
      MannaCore.instance.api.crateUtilMnemonicsGenerate(wordCount: wordCount);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<Mnemonics> newInstance({
    required String mnemonic,
    String? password,
  }) => MannaCore.instance.api.crateUtilMnemonicsNew(
    mnemonic: mnemonic,
    password: password,
  );

  @override
  int get hashCode => sentence.hashCode ^ entropy.hashCode ^ seedBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Mnemonics &&
          runtimeType == other.runtimeType &&
          sentence == other.sentence &&
          entropy == other.entropy &&
          seedBytes == other.seedBytes;
}

class U8Array32 extends NonGrowableListView<int> {
  static const arraySize = 32;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array32(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array32.init() : this(Uint8List(arraySize));
}

class U8Array33 extends NonGrowableListView<int> {
  static const arraySize = 33;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array33(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array33.init() : this(Uint8List(arraySize));
}

class U8Array64 extends NonGrowableListView<int> {
  static const arraySize = 64;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array64(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array64.init() : this(Uint8List(arraySize));
}
